// <auto-generated />
using System;
using GolfTrackerApp.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfTrackerApp.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329131616_UpdateTeeSetsModelChanges")]
    partial class UpdateTeeSetsModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GolfTrackerApp.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiInsightsOptOut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedPlayerId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiAuditLog", b =>
                {
                    b.Property<int>("AiAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiChatSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseReceived")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("AiAuditLogId");

                    b.HasIndex("AiChatSessionId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("ApplicationUserId", "RequestedAt");

                    b.ToTable("AiAuditLogs");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiChatSession", b =>
                {
                    b.Property<int>("AiChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AiChatSessionId");

                    b.HasIndex("ApplicationUserId", "LastMessageAt");

                    b.ToTable("AiChatSessions");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiChatSessionMessage", b =>
                {
                    b.Property<int>("AiChatSessionMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiChatSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("AiChatSessionMessageId");

                    b.HasIndex("AiChatSessionId", "Timestamp");

                    b.ToTable("AiChatSessionMessages");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiProviderSettings", b =>
                {
                    b.Property<int>("AiProviderSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("AiProviderSettingsId");

                    b.HasIndex("ProviderName")
                        .IsUnique();

                    b.ToTable("AiProviderSettings");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.ClubMembership", b =>
                {
                    b.Property<int>("ClubMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfClubId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubMembershipId");

                    b.HasIndex("UserId");

                    b.HasIndex("GolfClubId", "UserId")
                        .IsUnique();

                    b.ToTable("ClubMemberships");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfClub", b =>
                {
                    b.Property<int>("GolfClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountyOrRegion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("GolfClubId");

                    b.ToTable("GolfClubs");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfCourse", b =>
                {
                    b.Property<int>("GolfCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfHoles")
                        .HasColumnType("INTEGER");

                    b.HasKey("GolfCourseId");

                    b.HasIndex("GolfClubId");

                    b.ToTable("GolfCourses");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfSociety", b =>
                {
                    b.Property<int>("GolfSocietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GolfSocietyId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("GolfSocieties");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Hole", b =>
                {
                    b.Property<int>("HoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LengthYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Par")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrokeIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoleId");

                    b.HasIndex("GolfCourseId");

                    b.ToTable("Holes");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.HoleTee", b =>
                {
                    b.Property<int>("HoleTeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LengthYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Par")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrokeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeeSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoleTeeId");

                    b.HasIndex("TeeSetId");

                    b.HasIndex("HoleId", "TeeSetId")
                        .IsUnique();

                    b.ToTable("HoleTees");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Handicap")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.PlayerConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestingUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("RequestingUserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("PlayerConnections");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.PlayerMergeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestingUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundsMerged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourcePlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestingUserId");

                    b.HasIndex("SourcePlayerId");

                    b.HasIndex("TargetPlayerId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("PlayerMergeRequests");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("GolfCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingHole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("GolfCourseId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.RoundPlayer", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeeSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeeSetId");

                    b.ToTable("RoundPlayers");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FairwayHit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Putts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strokes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeeSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScoreId");

                    b.HasIndex("HoleId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoundId");

                    b.HasIndex("TeeSetId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.SocietyMembership", b =>
                {
                    b.Property<int>("SocietyMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfSocietyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SocietyMembershipId");

                    b.HasIndex("UserId");

                    b.HasIndex("GolfSocietyId", "UserId")
                        .IsUnique();

                    b.ToTable("SocietyMemberships");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.TeeSet", b =>
                {
                    b.Property<int>("TeeSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CourseRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolfCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SlopeRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeeSetId");

                    b.HasIndex("GolfCourseId", "Name")
                        .IsUnique();

                    b.ToTable("TeeSets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Data.ApplicationUser", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.Player", "LinkedPlayer")
                        .WithMany()
                        .HasForeignKey("LinkedPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedPlayer");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiAuditLog", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.AiChatSession", "AiChatSession")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AiChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiChatSession");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiChatSession", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiChatSessionMessage", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.AiChatSession", "AiChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("AiChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiChatSession");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.ClubMembership", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.GolfClub", "GolfClub")
                        .WithMany("ClubMemberships")
                        .HasForeignKey("GolfClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "User")
                        .WithMany("ClubMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfClub");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfCourse", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.GolfClub", "GolfClub")
                        .WithMany("GolfCourses")
                        .HasForeignKey("GolfClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfClub");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfSociety", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Hole", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.GolfCourse", "GolfCourse")
                        .WithMany("Holes")
                        .HasForeignKey("GolfCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfCourse");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.HoleTee", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.Hole", "Hole")
                        .WithMany("HoleTees")
                        .HasForeignKey("HoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.TeeSet", "TeeSet")
                        .WithMany("HoleTees")
                        .HasForeignKey("TeeSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hole");

                    b.Navigation("TeeSet");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Notification", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Player", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CreatedByApplicationUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.PlayerConnection", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "RequestingUser")
                        .WithMany()
                        .HasForeignKey("RequestingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestingUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.PlayerMergeRequest", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "RequestingUser")
                        .WithMany()
                        .HasForeignKey("RequestingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.Player", "SourcePlayer")
                        .WithMany()
                        .HasForeignKey("SourcePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.Player", "TargetPlayer")
                        .WithMany()
                        .HasForeignKey("TargetPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestingUser");

                    b.Navigation("SourcePlayer");

                    b.Navigation("TargetPlayer");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Round", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.GolfCourse", "GolfCourse")
                        .WithMany("Rounds")
                        .HasForeignKey("GolfCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("GolfCourse");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.RoundPlayer", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.Player", "Player")
                        .WithMany("RoundPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.Round", "Round")
                        .WithMany("RoundPlayers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.TeeSet", "TeeSet")
                        .WithMany()
                        .HasForeignKey("TeeSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("TeeSet");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Score", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.Hole", "Hole")
                        .WithMany("Scores")
                        .HasForeignKey("HoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.Round", "Round")
                        .WithMany("Scores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Models.TeeSet", "TeeSet")
                        .WithMany()
                        .HasForeignKey("TeeSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Hole");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("TeeSet");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.SocietyMembership", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.GolfSociety", "GolfSociety")
                        .WithMany("Memberships")
                        .HasForeignKey("GolfSocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", "User")
                        .WithMany("SocietyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfSociety");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.TeeSet", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Models.GolfCourse", "GolfCourse")
                        .WithMany("TeeSets")
                        .HasForeignKey("GolfCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GolfCourse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GolfTrackerApp.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("ClubMemberships");

                    b.Navigation("SocietyMemberships");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.AiChatSession", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfClub", b =>
                {
                    b.Navigation("ClubMemberships");

                    b.Navigation("GolfCourses");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfCourse", b =>
                {
                    b.Navigation("Holes");

                    b.Navigation("Rounds");

                    b.Navigation("TeeSets");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.GolfSociety", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Hole", b =>
                {
                    b.Navigation("HoleTees");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Player", b =>
                {
                    b.Navigation("RoundPlayers");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.Round", b =>
                {
                    b.Navigation("RoundPlayers");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfTrackerApp.Web.Models.TeeSet", b =>
                {
                    b.Navigation("HoleTees");
                });
#pragma warning restore 612, 618
        }
    }
}
