using System.Collections.Concurrent;
using GolfTrackerApp.Web.Models;
using GolfTrackerApp.Web.Services.AiProviders;

namespace GolfTrackerApp.Web.Services
{
    public class AiRoutingService : IAiRoutingService
    {
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILogger<AiRoutingService> _logger;
        private readonly ILoggerFactory _loggerFactory;

        private static readonly ConcurrentDictionary<string, DateTime> _circuitBreakerState = new();
        private static readonly TimeSpan CircuitBreakerCooldown = TimeSpan.FromMinutes(5);

        public AiRoutingService(
            IConfiguration configuration,
            IHttpClientFactory httpClientFactory,
            ILogger<AiRoutingService> logger,
            ILoggerFactory loggerFactory)
        {
            _configuration = configuration;
            _httpClientFactory = httpClientFactory;
            _logger = logger;
            _loggerFactory = loggerFactory;
        }

        public async Task<AiInsightResult> RouteCompletionAsync(
            string systemPrompt, string userPrompt,
            int? maxTokens = null, double? temperature = null,
            CancellationToken cancellationToken = default)
        {
            var providersSection = _configuration.GetSection("AiInsights:Providers");
            var providers = new List<AiProviderConfig>();
            foreach (var child in providersSection.GetChildren())
            {
                var config = child.Get<AiProviderConfig>() ?? new AiProviderConfig();
                config.Name = child.Key;
                providers.Add(config);
            }

            var effectiveMaxTokens = maxTokens
                ?? _configuration.GetValue<int>("AiInsights:MaxTokens");
            var effectiveTemperature = temperature
                ?? _configuration.GetValue<double>("AiInsights:Temperature");

            var enabledProviders = providers
                .Where(p => p.Enabled && !string.IsNullOrEmpty(p.ApiKey))
                .OrderBy(p => p.Priority)
                .ToList();

            if (!enabledProviders.Any())
            {
                return new AiInsightResult
                {
                    Success = false,
                    ErrorMessage = "No AI providers are configured and enabled."
                };
            }

            foreach (var config in enabledProviders)
            {
                if (_circuitBreakerState.TryGetValue(config.Name, out var failedAt)
                    && DateTime.UtcNow - failedAt < CircuitBreakerCooldown)
                {
                    _logger.LogDebug("Skipping provider {Provider} — circuit breaker active", config.Name);
                    continue;
                }

                try
                {
                    var provider = CreateProvider(config);
                    var result = await provider.GenerateCompletionAsync(
                        systemPrompt, userPrompt,
                        effectiveMaxTokens, effectiveTemperature,
                        cancellationToken);

                    if (result.Success)
                    {
                        _circuitBreakerState.TryRemove(config.Name, out _);
                        _logger.LogInformation(
                            "AI insight generated by {Provider} ({Tokens} tokens)",
                            config.Name, result.TokensUsed);
                        return result;
                    }

                    _logger.LogWarning(
                        "Provider {Provider} returned unsuccessful: {Error}",
                        config.Name, result.ErrorMessage);
                }
                catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex,
                        "Provider {Provider} failed, trying next", config.Name);
                    _circuitBreakerState[config.Name] = DateTime.UtcNow;
                }
            }

            return new AiInsightResult
            {
                Success = false,
                ErrorMessage = "All AI providers failed. Please try again later."
            };
        }

        private IAiProviderService CreateProvider(AiProviderConfig config)
        {
            var httpClient = _httpClientFactory.CreateClient($"AiProvider_{config.Name}");
            return config.Name switch
            {
                "OpenAI" => new OpenAiProviderService(httpClient, config,
                    _loggerFactory.CreateLogger<OpenAiProviderService>()),
                "Anthropic" => new AnthropicProviderService(httpClient, config,
                    _loggerFactory.CreateLogger<AnthropicProviderService>()),
                "Gemini" => new GeminiProviderService(httpClient, config,
                    _loggerFactory.CreateLogger<GeminiProviderService>()),
                "Mistral" => new MistralProviderService(httpClient, config,
                    _loggerFactory.CreateLogger<MistralProviderService>()),
                _ => throw new ArgumentException($"Unknown AI provider: {config.Name}")
            };
        }
    }
}
